# Site settings
title: Steven's Blog
email: steven.xu13@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog.
baseurl: ""
url: "http://blog.sxu.ca"
github_username:  stevenwenxu
plugins:
    - jekyll-redirect-from
whitelist:
    - jekyll-redirect-from

# Build settings
markdown: kramdown
highlighter: rouge
