# Site settings
title: Steven's Blog
email: steven.xu13@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog.
baseurl: "/blog"
url: "http://sxu.ca"
github_username:  steven-xu94

# Build settings
markdown: kramdown
highlighter: pygments